### ISSUE TITLE
Publish Docker image to Docker Hub

### ISSUE THREAD

**Issue by nexmoe** [nexmoe/roam-space#22]

**Comment by Arnab7456** [comment]
Use the following command to log in to your Docker Hub account:
`docker login`

Build Docker Image 

`docker build -t yourusername/your-repo:tag .`

Tag the image with your Docker Hub repository information:

`docker tag yourusername/your-repo:tag yourusername/your-repo:latest`

Push the Image to Docker Hub

`docker push yourusername/your-repo:tag`

if this solution is working  , can I create a pull req & you marge it ?

**Comment by nexmoe** [comment]
https://github.com/nexmoe/roam-space/pull/117
